kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployments
spec:
  replicas: 2
  selector:
    matchLabels:
      objtype: deployment
  template:
    metadata:
      name: deployment
      labels:
        objtype: deployment
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello; sleep 5; done"]
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "200m"
