kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    myname: pavan
  template:
    metadata:
      name: testpod
      labels:
        myname: pavan
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; echo Hello World; sleep 5s; done"]

