kind: PersistentVolume
apiVersion: v1
metadata:
  name: myebsvolume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-05840ac33d787d766
    fsType: ext4
