apiVersion: v1
kind: Pod
metadata:
  name: resource
spec:
  containers:
    - name: resource
      image: centos
      command: ["/bin/bash", "-c", "while true; do echo Hello-World; sleep 5; done"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
