apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: catalog
resources:
  - namespace.yaml
  - secrets.yaml
  - service-mysql-db.yaml
  - service-nodePort-mysql-db.yaml
  - statefulset-mysql-db.yaml
  - catalog-serviceaccount.yaml
  - catalog-configmap.yaml
  - catalog-service.yaml
  - catalog-service-NodePort.yaml
  - catalog-deployment.yaml
  #- service-ingress-multiple-pattern.yaml
  - service-mysql-db-pvc.yaml
  #- statefulset-mysql-db-pvc.yaml
patches:
  - path: deployment-scaleup-custom.yaml
  - path: statefulset-mysql-db-scaleup-custom.yaml
  - path: configmap-custom.yaml
