apiVersion: v1 
kind: Service
metadata:
  name: orders-postgresql-nodeport
  labels:
    app.kubernetes.io/created-by: eks-workshop
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: postgresql
      nodePort: 30020
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: orders
    app.kubernetes.io/component: postgresql