apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mycron
        spec:
          containers:
          - name: kube-cron-job
            image:  devopscube/kubernetes-job-demo:latest
            args: ["100"]
          restartPolicy: OnFailure
