kind: Pod
apiVersion: v1
metadata:
  name: myconfigmappod
spec:
  containers:
    - name: c01
      image: centos
      command: ["/bin/bash", "-c", "while true; do echo Hello world; sleep 10; done;"]
      volumeMounts:
        - name: testconfigmap
          mountPath: "/tmp/config" # config files will be mounted as readonly by default here
  volumes:
    - name: testconfigmap
      configMap:
        name: mymap # this should match the config map name created in the first step
        items:
          - key: sample.conf
            path: sample.conf
          
