kind: Pod
apiVersion: v1
metadata:
  name: myvolsecretpod
spec:
  containers:
    - name: c1
      image: centos
      command: ["/bin/bash", "-c", "while true; do echo Hello; sleep 5; done"]
      volumeMounts:
        - name: testsecret
          mountPath: "/tmp/mysecrets" # the secret files will be mounted as ReadOnly bydefault
  volumes:
    - name: testsecret
      secret:
        secretName: mysecret
