apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            cpu: "200"
            memory: "256Mi"
          requests:
            cpu: "100"
            memory: "128Mi"