version: '3'

services:
  mysql:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: auth
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth1234
      MYSQL_ROOT_PASSWORD: pavan1234
    ports:
      - 3306:3306
    volumes:
      - /home/ec2-user/mysql:/var/lib/mysql